/* 
 * ASP-NET-CORE-BELARUS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Product
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProductTests
    {
        // TODO uncomment below to declare an instance variable for Product
        //private Product instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Product
            //instance = new Product();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Product
        /// </summary>
        [Test]
        public void ProductInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Product
            //Assert.IsInstanceOfType<Product> (instance, "variable 'instance' is a Product");
        }


        /// <summary>
        /// Test the property 'ProductID'
        /// </summary>
        [Test]
        public void ProductIDTest()
        {
            // TODO unit test for the property 'ProductID'
        }
        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Test]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }
        /// <summary>
        /// Test the property 'SupplierID'
        /// </summary>
        [Test]
        public void SupplierIDTest()
        {
            // TODO unit test for the property 'SupplierID'
        }
        /// <summary>
        /// Test the property 'CategoryID'
        /// </summary>
        [Test]
        public void CategoryIDTest()
        {
            // TODO unit test for the property 'CategoryID'
        }
        /// <summary>
        /// Test the property 'QuantityPerUnit'
        /// </summary>
        [Test]
        public void QuantityPerUnitTest()
        {
            // TODO unit test for the property 'QuantityPerUnit'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitsInStock'
        /// </summary>
        [Test]
        public void UnitsInStockTest()
        {
            // TODO unit test for the property 'UnitsInStock'
        }
        /// <summary>
        /// Test the property 'UnitsOnOrder'
        /// </summary>
        [Test]
        public void UnitsOnOrderTest()
        {
            // TODO unit test for the property 'UnitsOnOrder'
        }
        /// <summary>
        /// Test the property 'ReorderLevel'
        /// </summary>
        [Test]
        public void ReorderLevelTest()
        {
            // TODO unit test for the property 'ReorderLevel'
        }
        /// <summary>
        /// Test the property 'Discontinued'
        /// </summary>
        [Test]
        public void DiscontinuedTest()
        {
            // TODO unit test for the property 'Discontinued'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }

    }

}
