/* 
 * ASP-NET-CORE-BELARUS API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Stream
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamTests
    {
        // TODO uncomment below to declare an instance variable for Stream
        //private Stream instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Stream
            //instance = new Stream();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Stream
        /// </summary>
        [Test]
        public void StreamInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Stream
            //Assert.IsInstanceOfType<Stream> (instance, "variable 'instance' is a Stream");
        }


        /// <summary>
        /// Test the property 'CanRead'
        /// </summary>
        [Test]
        public void CanReadTest()
        {
            // TODO unit test for the property 'CanRead'
        }
        /// <summary>
        /// Test the property 'CanSeek'
        /// </summary>
        [Test]
        public void CanSeekTest()
        {
            // TODO unit test for the property 'CanSeek'
        }
        /// <summary>
        /// Test the property 'CanTimeout'
        /// </summary>
        [Test]
        public void CanTimeoutTest()
        {
            // TODO unit test for the property 'CanTimeout'
        }
        /// <summary>
        /// Test the property 'CanWrite'
        /// </summary>
        [Test]
        public void CanWriteTest()
        {
            // TODO unit test for the property 'CanWrite'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'ReadTimeout'
        /// </summary>
        [Test]
        public void ReadTimeoutTest()
        {
            // TODO unit test for the property 'ReadTimeout'
        }
        /// <summary>
        /// Test the property 'WriteTimeout'
        /// </summary>
        [Test]
        public void WriteTimeoutTest()
        {
            // TODO unit test for the property 'WriteTimeout'
        }

    }

}
